spring.application.name=nature-guard-backend

server.port=3333

spring.datasource.url=jdbc:postgresql://localhost:5432/natureguard
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

file.upload-dir=./uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=30MB

# CORS Configuration - Development
cors.allowed-origins=http://localhost:5173,http://localhost:3000,http://localhost:8080

spring.output.ansi.enabled=ALWAYS